import { BugfixReportSchema, type BugfixReport } from '../domain/index.js';

const renderList = (items: string[], emptyLabel = 'None') =>
  items.length === 0 ? emptyLabel : items.map((item) => `- ${item}`).join('\n');

export const renderBugfixReportCli = (input: BugfixReport) => {
  const report = BugfixReportSchema.parse(input);

  return [
    'Bugfix Report',
    `Report ID: ${report.report_id}`,
    `Run ID: ${report.run_id}`,
    `Final Status: ${report.final_status}`,
    `Issue Ref: ${report.issue_ref}`,
    `Generated At: ${report.generated_at}`,
    `Config Version: ${report.config_version}`,
    '',
    'Requirement Refs',
    renderList(report.requirement_refs),
    '',
    'Code Locations',
    renderList(report.code_locations),
    '',
    'Root Cause Summary',
    report.root_cause_summary,
    '',
    'Fix Summary',
    report.fix_summary,
    '',
    'Verification Summary',
    report.verification_summary,
    '',
    'Artifacts',
    renderList(report.artifacts),
    '',
    'External Outcomes',
    renderList(report.external_outcomes),
    '',
    'Jira Writeback',
    report.jira_writeback_summary,
    '',
    'Feishu Record',
    report.feishu_record_summary,
    '',
    'Approval History',
    renderList(report.approval_history),
    '',
    'Open Risks',
    renderList(report.open_risks),
    '',
    'Failure Summary',
    report.failure_summary ?? 'None',
  ].join('\n');
};

export const renderBugfixReportMarkdown = (input: BugfixReport) => {
  const report = BugfixReportSchema.parse(input);

  return [
    '# Bugfix Report',
    '',
    `- Report ID: ${report.report_id}`,
    `- Run ID: ${report.run_id}`,
    `- Final Status: ${report.final_status}`,
    `- Issue Ref: ${report.issue_ref}`,
    `- Generated At: ${report.generated_at}`,
    `- Config Version: ${report.config_version}`,
    '',
    '## Requirement Refs',
    renderList(report.requirement_refs),
    '',
    '## Code Locations',
    renderList(report.code_locations),
    '',
    '## Root Cause Summary',
    '',
    report.root_cause_summary,
    '',
    '## Fix Summary',
    '',
    report.fix_summary,
    '',
    '## Verification Summary',
    '',
    report.verification_summary,
    '',
    '## Artifacts',
    renderList(report.artifacts),
    '',
    '## External Outcomes',
    renderList(report.external_outcomes),
    '',
    '## Jira Writeback',
    '',
    report.jira_writeback_summary,
    '',
    '## Feishu Record',
    '',
    report.feishu_record_summary,
    '',
    '## Approval History',
    renderList(report.approval_history),
    '',
    '## Open Risks',
    renderList(report.open_risks),
    '',
    '## Failure Summary',
    '',
    report.failure_summary ?? 'None',
  ].join('\n');
};

export const renderBugfixReportJson = (input: BugfixReport) =>
  JSON.stringify(BugfixReportSchema.parse(input), null, 2);
